### ISSUE TITLE
OpenSSL error when trying to send emails

### ISSUE THREAD

**Issue by Skyslycer** [ItzNotABug/ghosler#50]
`[2024-04-29 16:34:35 UTC] => [ERROR] => Newsletter: Error: D8B9EB2E457F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354`

That's the only thing I get. This is my docker-compose file:
version: '3.8'

```
services:
  ghosler:
    image: itznotabug/ghosler:0.97
    ports:
      - "2369:2369"
    networks:
      - revprox
    volumes:
      - "/opt/ghosler/logs:/usr/src/app/.logs"
      - "/opt/ghosler/analytics:/usr/src/app/files"
      - "/opt/ghosler/configuration:/usr/src/app/configuration"
    restart: always

networks:
  revprox:
    external: true
```
